=== Box-In-Box/solar_system/solar_system.dtd
<!ELEMENT root (information, planets, scientists)>

<!ELEMENT information (notice, since, description+, image)>

<!ELEMENT planets (planet+)>
<!ELEMENT planet (name+, diameter, distance, rotation_period, revolution_period, description+, image)>

<!ELEMENT scientists (scientist+)>
<!ELEMENT scientist (name+, description+, image)>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name nameType CDATA #REQUIRED>

<!ELEMENT notice (#PCDATA)>
<!ELEMENT since (#PCDATA)>
<!ELEMENT description (#PCDATA)>


<!ELEMENT diameter (#PCDATA)>
<!ELEMENT distance (#PCDATA)>
<!ELEMENT rotation_period (#PCDATA)>
<!ELEMENT revolution_period (#PCDATA)>
<!ATTLIST revolution_period timeType CDATA #REQUIRED>

<!ELEMENT image EMPTY>
<!ATTLIST image 
    src CDATA #REQUIRED
    height CDATA #REQUIRED
    width CDATA #REQUIRED>

<!ENTITY Johannes_Kepler_description SYSTEM "scientists/Johannes_Kepler/description.txt">

=== Box-In-Box/solar_system/solar_system.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="solar_system.xsl"?>
<!DOCTYPE root SYSTEM "solar_system.dtd">
<root>

    <information>
        <notice>태양계</notice>
        <since>46억년 전 초신성 대폭발</since>
        <description>&des1;</description>
        <description>&des2;</description>
        <image id="logo" src="etc/logo.gif" width="100" height="100"/>
        <image id="system" src="etc/system.gif" width="1200" height="675"/>
        <links>
            <link name="우주의 끝을 찾아서">잠 안올 때 듣던 영상</link>
            <link name="태양계 행성 순서">행성들 특징 참고 블로그</link>
            <link name="태양계 정리">행성 표 참고 블로그</link>
            <link name="한국천문연구원">행성 이미지 링크 사이트</link>
        </links>
    </information>

    <planets>
        <planet>
            <name nameType="Korean">수성</name>
            <name nameType="English">mercury</name>
            <diameter>4878</diameter>
            <distance>57900000</distance>
            <rotation_period>58.6</rotation_period>
            <revolution_period timeType="days">87.97</revolution_period>
            <description>태양과 가장 가까운 행성 이며, 태양계 생성 중에서 가장 크기가 작으며 평균온도 179℃ 이지만, -183℃ ~ 427℃로 온도변화가 매우 심하다.</description>
            <image src="planets/mercury.png" width="480" height="360"/>
        </planet>
        
        <planet>
            <name nameType="Korean">금성</name>
            <name nameType="English">venus</name>
            <diameter>12104</diameter>
            <distance>108200000</distance>
            <rotation_period>243</rotation_period>
            <revolution_period timeType="days">224.7</revolution_period>
            <description>시계방향으로 자전을 하며, 눈부시도록 밝은 금성의 모습 때문에 사랑과 미의 여신 비너스라는 이름을 가졌으며 지구와 비슷한 생겨서 쌍둥이 행성, 샛별이라는 별명도 있다.</description>
            <image src="planets/venus.png" width="480" height="360"/>
        </planet>

        <planet>
            <name nameType="Korean">지구</name>
            <name nameType="English">earth</name>
            <diameter>12756</diameter>
            <distance>149600000</distance>
            <rotation_period>1</rotation_period>
            <revolution_period timeType="days">365.26</revolution_period>
            <description>달이라는 위성을 가지고 있으며, 생명체가 살 수 있는 최적화된 조건이 형성되어 있다.</description>
            <image src="planets/earth.png" width="480" height="360"/>
        </planet>

        <planet>
            <name nameType="Korean">화성</name>
            <name nameType="English">mars</name>
            <diameter>6794</diameter>
            <distance>228000000</distance>
            <rotation_period>1.03</rotation_period>
            <revolution_period timeType="years">1.88</revolution_period>
            <description>지구와 비슷한 환경이 많이 관측 되면서 생물체가 살 수 있을 거다 라는 가설이 많이 나오게 되고, 지속적으로 연구가 진행중이다.</description>
            <image src="planets/mars.png" width="480" height="360"/>

        </planet>

        <planet>
            <name nameType="Korean">목성</name>
            <name nameType="English">jupiter</name>
            <diameter>142984</diameter>
            <distance>778300000</distance>
            <rotation_period>0.41</rotation_period>
            <revolution_period timeType="years">11.86</revolution_period>
            <description>태양계의 모든 행성들을 다 합쳐도 목성보다 작을 만큼 거대한 별이며, 또한 태양계 행성 중 자전속도가 제일 빠르다.</description>
            <image src="planets/jupiter.png" width="480" height="360"/>
        </planet>

        <planet>
            <name nameType="Korean">토성</name>
            <name nameType="English">saturn</name>
            <diameter>120536</diameter>
            <distance>1427000000</distance>
            <rotation_period>0.45</rotation_period>
            <revolution_period timeType="years">29.46</revolution_period>
            <description>행성 주변에 띠(고리)가 있는것이 특징이며, 고리의 너비는 약 7만km 이며, 얼음, 암석 등이 빽빽하게 연결 된 것이다.</description>
            <image src="planets/saturn.png" width="480" height="360"/>
        </planet>

        <planet>
            <name nameType="Korean">천왕성</name>
            <name nameType="English">uranus</name>
            <diameter>51118</diameter>
            <distance>2900000000</distance>
            <rotation_period>0.72</rotation_period>
            <revolution_period timeType="years">84.01</revolution_period>
            <description>시계방향으로 자전을 하며, 청왕성 역시 토성처럼 고리가 있지만 거리가 멀어 지구에서 쉽게 발견되지 못한다.</description>
            <image src="planets/uranus.png" width="480" height="360"/>
        </planet>

        <planet>
            <name nameType="Korean">해왕성</name>
            <name nameType="English">neptune</name>
            <diameter>49528</diameter>
            <distance>4497000000</distance>
            <rotation_period>0.67</rotation_period>
            <revolution_period timeType="years">164.79</revolution_period>
            <description>태양계에서 가장 먼 행성이며, 그로인해 가장 긴 공전시간을 가진다. 태양으로 받는 열에 비해 방출하는 열이 더 많아서 굉장히 추운 별이다.</description>
            <image src="planets/neptune.png" width="480" height="360"/>
        </planet>
    </planets>

    <scientists>
        <scientist>
            <name nameType="Korean">코페르니쿠스</name>
            <name nameType="English">Nikolaus Kopernikus</name>
            <description>&Nikolaus_Kopernikus_description;</description>
            <image src="scientists\Nikolaus_Kopernikus\Nikolaus_Kopernikus.jpg" width="256" height="350"/>
        </scientist>

        <scientist>
            <name nameType="Korean">갈릴레이</name>
            <name nameType="English">Galileo Galilei</name>
            <description>&Galileo_Galilei_description;</description>
            <image src="scientists\Galileo_Galilei\Galileo_Galilei.jpg" width="256" height="350"/>
        </scientist>

        <scientist>
            <name nameType="Korean">뉴턴</name>
            <name nameType="English">Isaac Newton</name>
            <description>&Isaac_Newton_description;</description>
            <image src="scientists\Isaac_Newton\Isaac_Newton.jpg" width="256" height="350"/>
            <subImg>
                <image src="scientists\Isaac_Newton\equation.gif" width="123" height="57"/>
            </subImg>
        </scientist>

        <scientist>
            <name nameType="Korean">케플러</name>
            <name nameType="English">Johannes Kepler</name>
            <description>&Johannes_Kepler_description;</description>
            <image src="scientists\Johannes_Kepler\Johannes_Kepler.jpg" width="256" height="350"/>
            <subImg>
                <image src="scientists\Johannes_Kepler\Kepler_1st_law.gif" width="464" height="304"/>
                <image src="scientists\Johannes_Kepler\Kepler_2nd_law.gif" width="487" height="301"/>
                <image src="scientists\Johannes_Kepler\Kepler_3rd_law.gif" width="250" height="374"/>
            </subImg>
        </scientist>
    </scientists>

</root>
